# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Visualização de Dados
author:
  name: Emanuele Santos
  email: emanuele@dc.ufc.br
  
description: > # this means to ignore newlines until "baseurl:"
  Página da Disciplina de Visualização de Dados, do curso de Ciência da 
  Computação (Graduação e Pós) da Universidade Federal do Ceará.
baseurl: "/datavis-course" # the subpath of your site, e.g. /blog
url: "https://emanueles.github.io" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: G-BZZ2FTQ9ST

minima: 
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/emanueles" }
    - { platform: instagram,      user_url: "https://www.instagram.com/prof.manu.ufc" }
    - { platform: twitter,        user_url: "https://twitter.com/emanueles" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@emanueles" }
  

show_drafts: false

collections:
  tasks:
      layout: page
      output: true
      paginate: 5

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
